[package]
name = "fuzzamoto-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
fuzz = ["reduced_pow"]
reproduce = ["reduced_pow"]
erlay = ["fuzzamoto/erlay"]
# Match a target built with target-patches/bitcoin-core-erlay-collisions.patch
erlay_collisions = ["erlay"]

reduced_pow = []

[lints]
workspace = true

[dependencies]
fuzzamoto = { path = "../fuzzamoto" }

rand = { version = "0.8.5", features = ["small_rng"] }
bitcoin = "0.32.0"
serde = { version = "1.0.197", features = ["derive"] }
postcard = { version = "1.1.1", features = ["alloc"], default-features = false }
log = "0.4.27"
murmurs = { version = "1.0.0" }

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "builder_bench"
harness = false
